package appeng.helpers;

public enum MonitorableAction {
    SPLIT_OR_PLACE_SINGLE,
    PICKUP_OR_SET_DOWN,
    SHIFT_CLICK,
    PICKUP_SINGLE,
    ROLL_UP,
    ROLL_DOWN,
    MOVE_REGION,
    AUTO_CRAFT,
    CREATIVE_DUPLICATE,
    SET_PIN,
    UNSET_PIN,
    FILL_SINGLE_CONTAINER,
    FILL_CONTAINERS,
    DRAIN_SINGLE_CONTAINER,
    DRAIN_CONTAINERS,
    CONTAINER_QUICK_TRANSFER
}
